// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// PENTING:
/// File ini adalah PLACEHOLDER. Anda harus menggantinya dengan menjalankan:
///   flutterfire configure
/// di root folder proyek setelah membuat project Firebase.
///
/// Tanpa konfigurasi yang benar, fitur Firebase tidak akan berfungsi.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVxO_3BN5Aj9MthG-xCMqOj3x2HVX_hI',
    appId: '1:1086776672640:web:b93607f7921d6ab06e0165',
    messagingSenderId: '1086776672640',
    projectId: 'documtrack',
    authDomain: 'documtrack.firebaseapp.com',
    storageBucket: 'documtrack.firebasestorage.app',
    measurementId: 'G-CWER65GXC7',
  );

  // Ganti placeholder berikut dengan nilai dari Firebase Console Anda.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhG_ZakvK8vwLc-AiQUnDI6WDcIrjNsvM',
    appId: '1:1086776672640:android:8d219b45226ee41d6e0165',
    messagingSenderId: '1086776672640',
    projectId: 'documtrack',
    storageBucket: 'documtrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYvZ7xLV1mrNOmFwiI074-SPJGD0AEPg',
    appId: '1:1086776672640:ios:7fa673a37ff753e06e0165',
    messagingSenderId: '1086776672640',
    projectId: 'documtrack',
    storageBucket: 'documtrack.firebasestorage.app',
    iosBundleId: 'com.example.tugas6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYvZ7xLV1mrNOmFwiI074-SPJGD0AEPg',
    appId: '1:1086776672640:ios:7fa673a37ff753e06e0165',
    messagingSenderId: '1086776672640',
    projectId: 'documtrack',
    storageBucket: 'documtrack.firebasestorage.app',
    iosBundleId: 'com.example.tugas6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZVxO_3BN5Aj9MthG-xCMqOj3x2HVX_hI',
    appId: '1:1086776672640:web:1cf62e56254797866e0165',
    messagingSenderId: '1086776672640',
    projectId: 'documtrack',
    authDomain: 'documtrack.firebaseapp.com',
    storageBucket: 'documtrack.firebasestorage.app',
    measurementId: 'G-KNW2J7VWCX',
  );

}