// screens/document_form_screen.dart

import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:exif/exif.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:image/image.dart' as img_lib;
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import '../models/document_item.dart';
import '../models/folder_item.dart';
import '../services/auth_service.dart';
import '../services/document_service.dart';
import '../services/file_service.dart';
import '../services/folder_service.dart';
import '../utils/app_strings.dart';

class DocumentFormScreen extends StatefulWidget {
  final DocumentItem? existingItem;
  final String initialFolderId;

  const DocumentFormScreen({
    super.key,
    this.existingItem,
    this.initialFolderId = '',
  });

  @override
  State<DocumentFormScreen> createState() => _DocumentFormScreenState();
}

class _DocumentFormScreenState extends State<DocumentFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  final _fileNameController = TextEditingController();

  final _authService = AuthService();
  final _docService = DocumentService();
  final _folderService = FolderService();
  final _fileService = FileService();
  final _picker = ImagePicker();

  File? _pickedFile;
  String? _pickedType;
  String _selectedFolderId = '';
  bool _isSaving = false;
  bool _isProcessing = false;

  Map<String, String> _pendingMetadata = {};

  bool get _isEdit => widget.existingItem != null;

  @override
  void initState() {
    super.initState();
    if (_isEdit) {
      _titleController.text = widget.existingItem!.title;
      _descController.text = widget.existingItem!.description;
      _fileNameController.text = widget.existingItem!.fileName;
      _selectedFolderId = widget.existingItem!.folderId;
    } else {
      _selectedFolderId = widget.initialFolderId;
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    _fileNameController.dispose();
    super.dispose();
  }

  /// Pick image dari KAMERA via image_picker (filename auto-generated by camera).
  Future<void> _pickImageFromCamera() async {
    final picked = await _picker.pickImage(
      source: ImageSource.camera,
      requestFullMetadata: true,
    );
    if (picked == null) return;

    setState(() => _isProcessing = true);
    try {
      final originalFile = File(picked.path);
      final originalBytes = await originalFile.readAsBytes();
      final originalName = p.basename(picked.path);

      final meta = await _extractImageMetadata(originalBytes);
      final compressed = await _compressImage(originalBytes);

      final tempDir = await getTemporaryDirectory();
      final tempFile = File(p.join(tempDir.path, 'cam_$originalName'));
      await tempFile.writeAsBytes(compressed, flush: true);

      if (!mounted) return;
      setState(() {
        _pickedFile = tempFile;
        _pickedType = 'image';
        _pendingMetadata = meta;
        if (_fileNameController.text.isEmpty) {
          _fileNameController.text = originalName;
        }
        _isProcessing = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() => _isProcessing = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Gagal proses foto: $e')),
      );
    }
  }

  /// Pick image dari GALERI pakai image_picker (Android 13+ pakai Photo Picker
  /// yang preserve DISPLAY_NAME asli + EXIF). NO compression flags supaya
  /// image_picker tidak rename ke "scaled_xxx" dan tidak strip EXIF.
  Future<void> _pickImageFromGallery() async {
    final picked = await _picker.pickImage(
      source: ImageSource.gallery,
      requestFullMetadata: true, // minta full metadata (EXIF, dll)
    );
    if (picked == null) return;

    setState(() => _isProcessing = true);
    try {
      final originalFile = File(picked.path);
      final originalBytes = await originalFile.readAsBytes();

      // Coba dapat nama yang masuk akal:
      // 1. picked.name dari image_picker
      // 2. fallback ke basename(path) kalau picked.name junk
      String originalName = _bestFilename(picked.name, picked.path);

      final meta = await _extractImageMetadata(originalBytes);
      final compressed = await _compressImage(originalBytes);

      final tempDir = await getTemporaryDirectory();
      final safeName = _sanitizeName(originalName);
      final tempFile = File(p.join(tempDir.path, 'pick_$safeName'));
      await tempFile.writeAsBytes(compressed, flush: true);

      if (!mounted) return;
      setState(() {
        _pickedFile = tempFile;
        _pickedType = 'image';
        _pendingMetadata = meta;
        if (_fileNameController.text.isEmpty) {
          _fileNameController.text = originalName;
        }
        _isProcessing = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() => _isProcessing = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Gagal proses foto: $e')),
      );
    }
  }

  /// Pilih nama yang paling masuk akal — hindari pattern junk (cache,
  /// scaled, JPEG_<ts>_<id>) → fallback ke timestamp manual.
  String _bestFilename(String pickerName, String filePath) {
    bool looksJunk(String s) {
      final base = p.basenameWithoutExtension(s);
      if (RegExp(r'^\d+$').hasMatch(base)) return true; // hanya angka
      if (base.startsWith('scaled_')) return true;
      if (base.startsWith('image_picker')) return true;
      // pattern Samsung share cache: JPEG_<timestamp>_<id>
      if (RegExp(r'^JPEG_\d+_\d{15,}$').hasMatch(base)) return true;
      return false;
    }

    if (!looksJunk(pickerName) && pickerName.contains('.')) {
      return pickerName;
    }
    final fromPath = p.basename(filePath);
    if (!looksJunk(fromPath) && fromPath.contains('.')) {
      return fromPath;
    }
    // generate fallback dengan timestamp
    final now = DateTime.now();
    final ts =
        '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}_'
        '${now.hour.toString().padLeft(2, '0')}${now.minute.toString().padLeft(2, '0')}${now.second.toString().padLeft(2, '0')}';
    return 'IMG_$ts.jpg';
  }

  String _sanitizeName(String name) {
    return name.replaceAll(RegExp(r'[^a-zA-Z0-9._-]'), '_');
  }

  /// Kompresi dengan PRESERVE EXIF (termasuk GPS) + auto-rotate sesuai
  /// EXIF orientation supaya foto tidak menyamping di hasil download.
  Future<Uint8List> _compressImage(Uint8List input) async {
    final decoded = img_lib.decodeImage(input);
    if (decoded == null) return input;

    // bake orientation — rotate pixels sesuai EXIF Orientation tag,
    // lalu reset orientation ke 1. Foto akan upright di mana-mana.
    final oriented = img_lib.bakeOrientation(decoded);

    // simpan EXIF (sudah orientasi 1 setelah bakeOrientation)
    final exifData = oriented.exif;

    img_lib.Image working = oriented;
    if (oriented.width > 1080 || oriented.height > 1080) {
      if (oriented.width >= oriented.height) {
        working = img_lib.copyResize(oriented, width: 1080);
      } else {
        working = img_lib.copyResize(oriented, height: 1080);
      }
    }
    working.exif = exifData;

    int quality = 75;
    var bytes = img_lib.encodeJpg(working, quality: quality);

    while (bytes.length > 800000 && quality > 30) {
      quality -= 10;
      bytes = img_lib.encodeJpg(working, quality: quality);
    }

    if (bytes.length > 850000 && working.width > 720) {
      final resized = working.width >= working.height
          ? img_lib.copyResize(working, width: 720)
          : img_lib.copyResize(working, height: 720);
      resized.exif = exifData;
      bytes = img_lib.encodeJpg(resized, quality: 60);
    }

    return Uint8List.fromList(bytes);
  }

  /// Pick video dari GALERI via file_picker — preserve filename asli.
  /// (Camera video di-disable karena hampir pasti > 900 KB Firestore limit.)
  Future<void> _pickVideoFromGallery() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.video,
      allowMultiple: false,
    );
    if (result == null || result.files.isEmpty) return;

    final pf = result.files.first;
    if (pf.path == null) return;
    final f = File(pf.path!);
    final size = await f.length();
    final name = pf.name;

    setState(() {
      _pickedFile = f;
      _pickedType = 'video';
      _pendingMetadata = {'fileSize': '$size'};
      if (_fileNameController.text.isEmpty) {
        _fileNameController.text = name;
      }
    });
  }

  /// Baca EXIF + dimensi + ukuran file dari bytes asli.
  Future<Map<String, String>> _extractImageMetadata(Uint8List bytes) async {
    final result = <String, String>{};
    try {
      result['fileSize'] = '${bytes.length}';

      try {
        final ui.Image img = await decodeImageFromList(bytes);
        result['width'] = '${img.width}';
        result['height'] = '${img.height}';
      } catch (_) {}

      final tags = await readExifFromBytes(bytes);
      void put(String key, String tagName) {
        final t = tags[tagName];
        if (t != null && t.printable.trim().isNotEmpty) {
          result[key] = t.printable;
        }
      }

      put('dateTimeOriginal', 'EXIF DateTimeOriginal');
      put('dateTimeDigitized', 'EXIF DateTimeDigitized');
      put('dateTime', 'Image DateTime');
      put('make', 'Image Make');
      put('model', 'Image Model');
      put('iso', 'EXIF ISOSpeedRatings');
      put('aperture', 'EXIF FNumber');
      put('exposureTime', 'EXIF ExposureTime');
      put('focalLength', 'EXIF FocalLength');
      put('orientation', 'Image Orientation');
      put('software', 'Image Software');
      put('gpsLat', 'GPS GPSLatitude');
      put('gpsLatRef', 'GPS GPSLatitudeRef');
      put('gpsLng', 'GPS GPSLongitude');
      put('gpsLngRef', 'GPS GPSLongitudeRef');
    } catch (e) {
      debugPrint('Error reading metadata: $e');
    }
    return result;
  }

  void _showPickerSheet() {
    showModalBottomSheet(
      context: context,
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.photo_camera),
              title: Text(AppStrings.of(context, 'photo_camera')),
              onTap: () {
                Navigator.pop(ctx);
                _pickImageFromCamera();
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: Text(AppStrings.of(context, 'photo_gallery')),
              onTap: () {
                Navigator.pop(ctx);
                _pickImageFromGallery();
              },
            ),
            ListTile(
              leading: const Icon(Icons.video_library),
              title: Text(AppStrings.of(context, 'video_gallery')),
              subtitle: Text(AppStrings.of(context, 'video_size_hint')),
              onTap: () {
                Navigator.pop(ctx);
                _pickVideoFromGallery();
              },
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    if (!_isEdit && _pickedFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(AppStrings.of(context, 'media_required'))),
      );
      return;
    }

    setState(() => _isSaving = true);

    try {
      if (_isEdit) {
        await _docService.updateDocument(
          id: widget.existingItem!.id,
          title: _titleController.text.trim(),
          description: _descController.text.trim(),
          fileName: _fileNameController.text.trim(),
        );
      } else {
        final user = _authService.currentUser;
        if (user == null) throw Exception('User belum login');

        final base64Str = await _fileService.encodeFile(_pickedFile!);

        final newItem = DocumentItem(
          id: '',
          title: _titleController.text.trim(),
          description: _descController.text.trim(),
          fileName: _fileNameController.text.trim(),
          mediaBase64: base64Str,
          mediaType: _pickedType!,
          folderId: _selectedFolderId,
          userId: user.uid,
          createdAt: DateTime.now(),
          metadata: _pendingMetadata,
        );
        await _docService.addDocument(newItem);
      }

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(_isEdit
              ? AppStrings.of(context, 'doc_updated')
              : AppStrings.of(context, 'doc_saved')),
          backgroundColor: Colors.green,
        ),
      );
      Navigator.pop(context);
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
              'Gagal: ${e.toString().replaceFirst('Exception: ', '')}'),
          backgroundColor: Colors.red,
          duration: const Duration(seconds: 4),
        ),
      );
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  Widget _buildPreview() {
    if (_isProcessing) {
      return Container(
        color: Colors.grey.shade200,
        child: const Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CircularProgressIndicator(),
              SizedBox(height: 12),
              Text('Memproses foto...'),
            ],
          ),
        ),
      );
    }

    if (_pickedFile == null && _isEdit) {
      final item = widget.existingItem!;
      if (item.mediaType == 'video') {
        return Container(
          color: Colors.black87,
          child: const Center(
            child: Icon(Icons.videocam, color: Colors.white, size: 64),
          ),
        );
      }
      return Image.memory(
        _fileService.decode(item.mediaBase64),
        fit: BoxFit.cover,
      );
    }

    if (_pickedFile == null) {
      return Container(
        color: Colors.grey.shade200,
        child: const Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.add_a_photo, size: 48, color: Colors.grey),
              SizedBox(height: 8),
              Text('Belum ada media', style: TextStyle(color: Colors.grey)),
            ],
          ),
        ),
      );
    }

    if (_pickedType == 'video') {
      return Container(
        color: Colors.black87,
        child: const Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(Icons.videocam, color: Colors.white, size: 48),
              SizedBox(height: 8),
              Text('Video siap disimpan',
                  style: TextStyle(color: Colors.white70)),
            ],
          ),
        ),
      );
    }

    return Image.file(_pickedFile!, fit: BoxFit.cover);
  }

  Widget _buildFolderDropdown(String userId) {
    return StreamBuilder<List<FolderItem>>(
      stream: _folderService.streamFolders(userId),
      builder: (ctx, snap) {
        final folders = snap.data ?? [];
        final items = <DropdownMenuItem<String>>[
          DropdownMenuItem(
            value: '',
            child: Row(
              children: [
                const Icon(Icons.home, size: 18),
                const SizedBox(width: 8),
                Text(AppStrings.of(context, 'root')),
              ],
            ),
          ),
          ...folders.map(
            (f) => DropdownMenuItem(
              value: f.id,
              child: Row(
                children: [
                  Icon(Icons.folder, size: 18, color: f.color),
                  const SizedBox(width: 8),
                  Text(f.name),
                ],
              ),
            ),
          ),
        ];
        return DropdownButtonFormField<String>(
          value: items.any((i) => i.value == _selectedFolderId)
              ? _selectedFolderId
              : '',
          items: items,
          decoration: InputDecoration(
            labelText: AppStrings.of(context, 'folders'),
            prefixIcon: const Icon(Icons.folder_open),
          ),
          onChanged: _isEdit
              ? null
              : (val) {
                  if (val != null) {
                    setState(() => _selectedFolderId = val);
                  }
                },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = _authService.currentUser;
    return Scaffold(
      appBar: AppBar(
        title: Text(_isEdit
            ? AppStrings.of(context, 'edit_documentation')
            : AppStrings.of(context, 'add_documentation')),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: AspectRatio(
                    aspectRatio: 16 / 9,
                    child: _buildPreview(),
                  ),
                ),
                const SizedBox(height: 12),
                if (!_isEdit)
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      OutlinedButton.icon(
                        onPressed: (_isSaving || _isProcessing)
                            ? null
                            : _showPickerSheet,
                        icon: const Icon(Icons.attach_file),
                        label: Text(_pickedFile == null
                            ? AppStrings.of(context, 'pick_media')
                            : AppStrings.of(context, 'change_media')),
                      ),
                      const SizedBox(height: 6),
                      Text(
                        AppStrings.of(context, 'compress_note'),
                        style: const TextStyle(
                            fontSize: 11, color: Colors.grey),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  )
                else
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: Colors.amber.shade50,
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: Colors.amber.shade200),
                    ),
                    child: Row(
                      children: [
                        const Icon(Icons.info_outline,
                            size: 18, color: Colors.amber),
                        const SizedBox(width: 8),
                        Expanded(
                          child: Text(
                            AppStrings.of(context, 'edit_mode_note'),
                            style: const TextStyle(
                                fontSize: 12, color: Colors.black87),
                          ),
                        ),
                      ],
                    ),
                  ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _titleController,
                  decoration: InputDecoration(
                    labelText: AppStrings.of(context, 'title'),
                    prefixIcon: const Icon(Icons.title),
                  ),
                  validator: (val) {
                    if (val == null || val.trim().isEmpty) {
                      return AppStrings.of(context, 'title_required');
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _fileNameController,
                  decoration: InputDecoration(
                    labelText: AppStrings.of(context, 'file_name'),
                    prefixIcon: const Icon(Icons.insert_drive_file),
                    hintText: '20240425_180922.jpg',
                  ),
                  validator: (val) {
                    if (val == null || val.trim().isEmpty) {
                      return AppStrings.of(context, 'name_required');
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _descController,
                  maxLines: 4,
                  decoration: InputDecoration(
                    labelText: AppStrings.of(context, 'description'),
                    alignLabelWithHint: true,
                  ),
                ),
                const SizedBox(height: 12),
                if (user != null) _buildFolderDropdown(user.uid),
                const SizedBox(height: 24),
                ElevatedButton.icon(
                  onPressed: _isSaving ? null : _save,
                  icon: _isSaving
                      ? const SizedBox(
                          height: 18,
                          width: 18,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Icon(Icons.save),
                  label: Text(_isSaving
                      ? AppStrings.of(context, 'saving')
                      : AppStrings.of(context, 'save')),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
