// utils/app_strings.dart

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/locale_provider.dart';

/// Helper terjemahan sederhana — Indonesia (default) & English.
class AppStrings {
  static const Map<String, Map<String, String>> _values = {
    'id': {
      'app_title': 'DocumTracker',
      'login': 'Login',
      'register': 'Daftar',
      'register_account': 'Daftar Akun',
      'email': 'Email',
      'password': 'Password',
      'name': 'Nama',
      'name_required': 'Nama tidak boleh kosong',
      'email_required': 'Email tidak boleh kosong',
      'email_invalid': 'Format email tidak valid',
      'password_required': 'Password tidak boleh kosong',
      'password_min': 'Password minimal 6 karakter',
      'password_confirm': 'Konfirmasi Password',
      'password_mismatch': 'Password tidak sama',
      'no_account': 'Belum punya akun?',
      'tagline': 'Catat dokumentasi Anda',
      'logout': 'Logout',
      'add': 'Tambah',
      'add_document': 'Dokumentasi Baru',
      'add_folder': 'Folder Baru',
      'edit': 'Edit',
      'delete': 'Hapus',
      'cancel': 'Batal',
      'save': 'Simpan',
      'saving': 'Menyimpan...',
      'download': 'Download',
      'downloaded_to_gallery': 'Tersimpan di galeri sebagai',
      'no_documents': 'Belum ada dokumentasi',
      'no_documents_hint': 'Tekan tombol "Tambah" untuk membuat',
      'edit_documentation': 'Edit Dokumentasi',
      'add_documentation': 'Tambah Dokumentasi',
      'detail': 'Detail Dokumentasi',
      'title': 'Judul',
      'title_required': 'Judul tidak boleh kosong',
      'description': 'Deskripsi (opsional)',
      'file_name': 'Nama File',
      'pick_media': 'Pilih Foto / Video',
      'change_media': 'Ganti Media',
      'media_required': 'Foto atau video wajib diisi',
      'photo': 'Foto',
      'video': 'Video',
      'photo_camera': 'Foto dari Kamera',
      'photo_gallery': 'Foto dari Galeri',
      'video_camera': 'Video dari Kamera (max 10 detik)',
      'video_gallery': 'Video dari Galeri',
      'video_size_hint': 'Disarankan video pendek (<900 KB)',
      'edit_mode_note':
          'Mode edit: media tidak bisa diganti, hanya judul, deskripsi & nama file.',
      'compress_note':
          'Foto akan dikompresi otomatis. Video maksimal ~900 KB.',
      'no_description': 'Tidak ada deskripsi.',
      'delete_doc_title': 'Hapus Dokumentasi',
      'delete_doc_msg': 'Yakin ingin menghapus',
      'doc_deleted': 'Dokumentasi dihapus',
      'doc_saved': 'Dokumentasi disimpan',
      'doc_updated': 'Dokumentasi diperbarui',
      'login_as': 'Login sebagai',
      'settings': 'Pengaturan',
      'theme': 'Tema',
      'theme_light': 'Terang',
      'theme_dark': 'Gelap',
      'theme_system': 'Ikuti sistem',
      'language': 'Bahasa',
      'lang_id': 'Indonesia',
      'lang_en': 'English',
      'view_list': 'Tampilan List',
      'view_grid': 'Tampilan Grid',
      'sort_by': 'Urutkan',
      'sort_newest': 'Terbaru',
      'sort_oldest': 'Terlama',
      'sort_name_asc': 'Nama A-Z',
      'sort_name_desc': 'Nama Z-A',
      'folders': 'Folder',
      'files': 'File',
      'root': 'Beranda',
      'new_folder': 'Folder Baru',
      'folder_name': 'Nama Folder',
      'folder_name_required': 'Nama folder tidak boleh kosong',
      'folder_created': 'Folder dibuat',
      'folder_renamed': 'Folder diubah',
      'folder_deleted': 'Folder dihapus',
      'rename_folder': 'Ubah Nama Folder',
      'delete_folder_msg':
          'Yakin ingin menghapus folder ini? Isi folder tidak ikut terhapus, hanya pindah ke beranda.',
      'rename': 'Ubah Nama',
      'selected': 'dipilih',
      'select_all': 'Pilih Semua',
      'move': 'Pindahkan',
      'move_to': 'Pindahkan ke',
      'docs_moved': 'Dokumentasi dipindahkan',
      'delete_selected_title': 'Hapus Dokumentasi Terpilih',
      'delete_selected_msg': 'Yakin hapus {n} dokumentasi terpilih?',
      'no_folder_to_move': 'Belum ada folder. Buat folder dulu via tombol Tambah.',
      'account': 'Akun',
      'account_settings': 'Pengaturan Akun',
      'change_name': 'Ubah Nama',
      'change_email': 'Ubah Email',
      'change_password': 'Ubah Password',
      'current_password': 'Password Saat Ini',
      'new_password': 'Password Baru',
      'new_email': 'Email Baru',
      'new_name': 'Nama Baru',
      'updated': 'Berhasil diperbarui',
      'email_verify_sent':
          'Email verifikasi dikirim ke alamat baru. Klik link di sana untuk konfirmasi.',
      'change_color': 'Ubah Warna',
      'choose_color': 'Pilih Warna',
      'color_updated': 'Warna folder diperbarui',
      'metadata': 'Informasi Detail',
      'date_taken': 'Tanggal Diambil',
      'date_uploaded': 'Tanggal Diupload',
      'dimensions': 'Resolusi',
      'file_size': 'Ukuran',
      'camera': 'Kamera',
      'iso': 'ISO',
      'aperture': 'Aperture',
      'shutter': 'Shutter',
      'focal_length': 'Focal Length',
      'gps': 'Lokasi GPS',
      'orientation': 'Orientasi',
      'no_metadata': 'Tidak ada metadata tambahan.',
      'folders_selected': 'folder dipilih',
      'search_hint': 'Mau cari apa?',
      'no_results': 'Tidak ada hasil',
      'tab_gallery': 'Galeri',
      'tab_drive': 'Drive',
      'tab_upload': 'Baru',
      'tab_search': 'Cari',
      'devices': 'Perangkat',
      'locations': 'Lokasi',
      'videos': 'Video',
      'gifs': 'GIF',
      'unknown_location': 'Lokasi tak diketahui',
      'trash': 'Sampah',
      'trash_empty': 'Sampah kosong',
      'trash_hint':
          'Item akan dihapus permanen otomatis setelah 30 hari di sini.',
      'restore': 'Pulihkan',
      'delete_forever': 'Hapus Permanen',
      'delete_forever_confirm':
          'Hapus permanen item ini? Tidak bisa di-recover lagi.',
      'restored': 'Berhasil dipulihkan',
      'permanently_deleted': 'Dihapus permanen',
      'days_left': 'hari tersisa',
      'expires_today': 'Berakhir hari ini',
      'empty_trash': 'Kosongkan Sampah',
      'empty_trash_confirm': 'Hapus permanen semua item di sampah?',
      'moved_to_trash': 'Dipindah ke sampah',
    },
    'en': {
      'app_title': 'DocumTracker',
      'login': 'Login',
      'register': 'Register',
      'register_account': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'name_required': 'Name is required',
      'email_required': 'Email is required',
      'email_invalid': 'Invalid email format',
      'password_required': 'Password is required',
      'password_min': 'Password must be at least 6 characters',
      'password_confirm': 'Confirm Password',
      'password_mismatch': 'Passwords do not match',
      'no_account': "Don't have an account?",
      'tagline': 'Track your documentation',
      'logout': 'Logout',
      'add': 'Add',
      'add_document': 'New Documentation',
      'add_folder': 'New Folder',
      'edit': 'Edit',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'saving': 'Saving...',
      'download': 'Download',
      'downloaded_to_gallery': 'Saved to gallery as',
      'no_documents': 'No documentation yet',
      'no_documents_hint': 'Tap the "Add" button to create one',
      'edit_documentation': 'Edit Documentation',
      'add_documentation': 'Add Documentation',
      'detail': 'Documentation Detail',
      'title': 'Title',
      'title_required': 'Title is required',
      'description': 'Description (optional)',
      'file_name': 'File Name',
      'pick_media': 'Pick Photo / Video',
      'change_media': 'Change Media',
      'media_required': 'Photo or video is required',
      'photo': 'Photo',
      'video': 'Video',
      'photo_camera': 'Photo from Camera',
      'photo_gallery': 'Photo from Gallery',
      'video_camera': 'Video from Camera (max 10 seconds)',
      'video_gallery': 'Video from Gallery',
      'video_size_hint': 'Use short videos (<900 KB)',
      'edit_mode_note':
          'Edit mode: media cannot be changed, only title, description & file name.',
      'compress_note':
          'Photos will be auto-compressed. Videos max ~900 KB.',
      'no_description': 'No description.',
      'delete_doc_title': 'Delete Documentation',
      'delete_doc_msg': 'Delete',
      'doc_deleted': 'Documentation deleted',
      'doc_saved': 'Documentation saved',
      'doc_updated': 'Documentation updated',
      'login_as': 'Logged in as',
      'settings': 'Settings',
      'theme': 'Theme',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'Follow system',
      'language': 'Language',
      'lang_id': 'Indonesia',
      'lang_en': 'English',
      'view_list': 'List view',
      'view_grid': 'Grid view',
      'sort_by': 'Sort by',
      'sort_newest': 'Newest',
      'sort_oldest': 'Oldest',
      'sort_name_asc': 'Name A-Z',
      'sort_name_desc': 'Name Z-A',
      'folders': 'Folders',
      'files': 'Files',
      'root': 'Home',
      'new_folder': 'New Folder',
      'folder_name': 'Folder Name',
      'folder_name_required': 'Folder name is required',
      'folder_created': 'Folder created',
      'folder_renamed': 'Folder renamed',
      'folder_deleted': 'Folder deleted',
      'rename_folder': 'Rename Folder',
      'delete_folder_msg':
          'Delete this folder? Its contents will be moved back to home, not deleted.',
      'rename': 'Rename',
      'selected': 'selected',
      'select_all': 'Select All',
      'move': 'Move',
      'move_to': 'Move to',
      'docs_moved': 'Documents moved',
      'delete_selected_title': 'Delete Selected',
      'delete_selected_msg': 'Delete {n} selected documents?',
      'no_folder_to_move': 'No folders yet. Create one first via the Add button.',
      'account': 'Account',
      'account_settings': 'Account Settings',
      'change_name': 'Change Name',
      'change_email': 'Change Email',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'new_email': 'New Email',
      'new_name': 'New Name',
      'updated': 'Updated successfully',
      'email_verify_sent':
          'Verification email sent to the new address. Click the link there to confirm.',
      'change_color': 'Change Color',
      'choose_color': 'Choose Color',
      'color_updated': 'Folder color updated',
      'metadata': 'Detail Information',
      'date_taken': 'Date Taken',
      'date_uploaded': 'Date Uploaded',
      'dimensions': 'Resolution',
      'file_size': 'Size',
      'camera': 'Camera',
      'iso': 'ISO',
      'aperture': 'Aperture',
      'shutter': 'Shutter',
      'focal_length': 'Focal Length',
      'gps': 'GPS Location',
      'orientation': 'Orientation',
      'no_metadata': 'No additional metadata.',
      'folders_selected': 'folders selected',
      'search_hint': 'What are you looking for?',
      'no_results': 'No results',
      'tab_gallery': 'Gallery',
      'tab_drive': 'Drive',
      'tab_upload': 'New',
      'tab_search': 'Search',
      'devices': 'Devices',
      'locations': 'Locations',
      'videos': 'Videos',
      'gifs': 'GIFs',
      'unknown_location': 'Unknown location',
      'trash': 'Trash',
      'trash_empty': 'Trash is empty',
      'trash_hint':
          'Items here will be permanently deleted after 30 days.',
      'restore': 'Restore',
      'delete_forever': 'Delete Forever',
      'delete_forever_confirm':
          'Permanently delete this item? Cannot be recovered.',
      'restored': 'Restored',
      'permanently_deleted': 'Permanently deleted',
      'days_left': 'days left',
      'expires_today': 'Expires today',
      'empty_trash': 'Empty Trash',
      'empty_trash_confirm': 'Permanently delete all items in trash?',
      'moved_to_trash': 'Moved to trash',
    },
  };

  /// Selalu pakai read — MaterialApp sudah watch LocaleProvider di root,
  /// jadi seluruh tree akan rebuild saat ganti bahasa.
  static String of(BuildContext context, String key) {
    final code = context.read<LocaleProvider>().locale.languageCode;
    return _values[code]?[key] ?? _values['en']?[key] ?? key;
  }

  /// Alias supaya kompatibel dengan kode lama yang panggil .off()
  static String off(BuildContext context, String key) => of(context, key);
}
